server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jwt_test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.tanay.app: TRACE

app:
  jwtAccessTokenSecret: This-Is-Super-Secure-Key-For-JWT-By-Tanay-fsdfkjsdfsdk;jfsdkfksjldfklsdfl;jsdklf
  jwtAccessTokenExpirationInMs: 3600000 #60 minutes
  jwtRefreshTokenSecret: This-Is-Key-Secure-Tanay-For-JWT-By-fdsklfjsdklfsdklfjdslflsd;jfkdsfkl;sdjfklasnfklnsfsdklf
  jwtRefRefreshTokenExpirationInMs: 2592000000 #30 days